# Read about `build.yaml` at https://pub.dartlang.org/packages/build_config
builders:
  baseHrefBuilder:
    import: "package:basehref/builder.dart"
    builder_factories: ["baseHrefBuilder"]
    build_extensions: {".html": [".basehref.html"]}
    build_to: source
    auto_apply: root_package
    defaults:
      generate_for:
        include:
          - web/index.html
      #options:
      #  href: '/hello/'
