name: basehref
version: 0.0.4
description: builder to add or modify index.html base href tag
author: Alexandre Del Bigio <alescdb@users.noreply.github.com>
homepage: https://github.com/alescdb/basehref

environment:
  sdk: '>=2.0.0 <3.0.0'

dependencies:
  build: ^1.1.3
  build_config: ^0.3.1+4
  html: ^0.13.4+1
  logging: ^0.11.2

dev_dependencies:
  build_runner: ^1.3.1
  build_web_compilers: ^1.2.0
