name: basehref
version: 0.5.1
description: AngularDart and Dart (for the Web) builder to add or modify tag base href in index.html
author: Alexandre Del Bigio <alescdb@users.noreply.github.com>
homepage: https://github.com/alescdb/basehref

environment:
  sdk: '>=2.3.0 <3.0.0'

dependencies:
  build: ^1.1.4
  build_config: ^0.4.0
  html: ^0.14.0+2
  logging: ^0.11.3+2
  pedantic: ^1.7.0

dev_dependencies:
  build_runner: ^1.4.0
  build_web_compilers: ^2.0.0
